// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQfzwB-bHiRqNENsV1LhM_dtJ-XbkvZhU',
    appId: '1:941387471137:web:99a904a3f2cda8c2eac660',
    messagingSenderId: '941387471137',
    projectId: 'cekpaketaji',
    authDomain: 'cekpaketaji.firebaseapp.com',
    storageBucket: 'cekpaketaji.appspot.com',
    measurementId: 'G-TWGSZ17ZES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1N4_k6OlufOkqfabJrnB33udxDJ1CW-s',
    appId: '1:941387471137:android:ccaa455f77f1ecabeac660',
    messagingSenderId: '941387471137',
    projectId: 'cekpaketaji',
    storageBucket: 'cekpaketaji.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZZLDsUjHPmugb4aasHQnvFbNb9QMOarU',
    appId: '1:941387471137:ios:a99f6c4ae63b0c5eeac660',
    messagingSenderId: '941387471137',
    projectId: 'cekpaketaji',
    storageBucket: 'cekpaketaji.appspot.com',
    iosClientId:
        '941387471137-ts1dedvvh5eu75noh0aeh3l0pjrnug4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvcDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZZLDsUjHPmugb4aasHQnvFbNb9QMOarU',
    appId: '1:941387471137:ios:a99f6c4ae63b0c5eeac660',
    messagingSenderId: '941387471137',
    projectId: 'cekpaketaji',
    storageBucket: 'cekpaketaji.appspot.com',
    iosClientId:
        '941387471137-ts1dedvvh5eu75noh0aeh3l0pjrnug4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvcDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQfzwB-bHiRqNENsV1LhM_dtJ-XbkvZhU',
    appId: '1:941387471137:web:da37491046298f4deac660',
    messagingSenderId: '941387471137',
    projectId: 'cekpaketaji',
    authDomain: 'cekpaketaji.firebaseapp.com',
    storageBucket: 'cekpaketaji.appspot.com',
    measurementId: 'G-TFMSVC19C2',
  );
}
